/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Comeat Backend API
 * 多租户餐饮外卖系统后端API文档
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  Category,
  CommonCategoriesListParams,
  CommonMerchantUsersListParams,
  CommonProductsListParams,
  MerchantUser,
  PaginatedCategoryList,
  PaginatedMerchantUserList,
  PaginatedProductList,
  PatchedCategory,
  PatchedMerchantUser,
  PatchedProduct,
  Product
} from '../index.schemas';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;





export type commonCategoriesListResponse200 = {
  data: PaginatedCategoryList
  status: 200
}

export type commonCategoriesListResponseSuccess = (commonCategoriesListResponse200) & {
  headers: Headers;
};
;

export type commonCategoriesListResponse = (commonCategoriesListResponseSuccess)

export const getCommonCategoriesListUrl = (params?: CommonCategoriesListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/common/categories/?${stringifiedParams}` : `/api/v1/common/categories/`
}

export const commonCategoriesList = async (params?: CommonCategoriesListParams, options?: RequestInit): Promise<commonCategoriesListResponse> => {

  const res = await fetch(getCommonCategoriesListUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonCategoriesListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commonCategoriesListResponse
}





export const getCommonCategoriesListQueryKey = (params?: MaybeRef<CommonCategoriesListParams>,) => {
    return [
    'api','v1','common','categories', ...(params ? [params] : [])
    ] as const;
    }


export const getCommonCategoriesListQueryOptions = <TData = Awaited<ReturnType<typeof commonCategoriesList>>, TError = unknown>(params?: MaybeRef<CommonCategoriesListParams>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof commonCategoriesList>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getCommonCategoriesListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof commonCategoriesList>>> = ({ signal }) => commonCategoriesList(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof commonCategoriesList>>, TError, TData>
}

export type CommonCategoriesListQueryResult = NonNullable<Awaited<ReturnType<typeof commonCategoriesList>>>
export type CommonCategoriesListQueryError = unknown



export function useCommonCategoriesList<TData = Awaited<ReturnType<typeof commonCategoriesList>>, TError = unknown>(
 params?: MaybeRef<CommonCategoriesListParams>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof commonCategoriesList>>, TError, TData>, fetch?: RequestInit}

 ): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCommonCategoriesListQueryOptions(params,options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
}






export type commonCategoriesCreateResponse201 = {
  data: Category
  status: 201
}

export type commonCategoriesCreateResponseSuccess = (commonCategoriesCreateResponse201) & {
  headers: Headers;
};
;

export type commonCategoriesCreateResponse = (commonCategoriesCreateResponseSuccess)

export const getCommonCategoriesCreateUrl = () => {




  return `/api/v1/common/categories/`
}

export const commonCategoriesCreate = async (category: NonReadonly<Category>, options?: RequestInit): Promise<commonCategoriesCreateResponse> => {

  const res = await fetch(getCommonCategoriesCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      category,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonCategoriesCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commonCategoriesCreateResponse
}




export const getCommonCategoriesCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonCategoriesCreate>>, TError,{data: NonReadonly<Category>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof commonCategoriesCreate>>, TError,{data: NonReadonly<Category>}, TContext> => {

const mutationKey = ['commonCategoriesCreate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof commonCategoriesCreate>>, {data: NonReadonly<Category>}> = (props) => {
          const {data} = props ?? {};

          return  commonCategoriesCreate(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CommonCategoriesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof commonCategoriesCreate>>>
    export type CommonCategoriesCreateMutationBody = NonReadonly<Category>
    export type CommonCategoriesCreateMutationError = unknown

    export const useCommonCategoriesCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonCategoriesCreate>>, TError,{data: NonReadonly<Category>}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof commonCategoriesCreate>>,
        TError,
        {data: NonReadonly<Category>},
        TContext
      > => {
      return useMutation(getCommonCategoriesCreateMutationOptions(options));
    }
    export type commonCategoriesRetrieveResponse200 = {
  data: Category
  status: 200
}

export type commonCategoriesRetrieveResponseSuccess = (commonCategoriesRetrieveResponse200) & {
  headers: Headers;
};
;

export type commonCategoriesRetrieveResponse = (commonCategoriesRetrieveResponseSuccess)

export const getCommonCategoriesRetrieveUrl = (id: number,) => {




  return `/api/v1/common/categories/${id}/`
}

export const commonCategoriesRetrieve = async (id: number, options?: RequestInit): Promise<commonCategoriesRetrieveResponse> => {

  const res = await fetch(getCommonCategoriesRetrieveUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonCategoriesRetrieveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commonCategoriesRetrieveResponse
}





export const getCommonCategoriesRetrieveQueryKey = (id: MaybeRef<number>,) => {
    return [
    'api','v1','common','categories',id
    ] as const;
    }


export const getCommonCategoriesRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof commonCategoriesRetrieve>>, TError = unknown>(id: MaybeRef<number>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof commonCategoriesRetrieve>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getCommonCategoriesRetrieveQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof commonCategoriesRetrieve>>> = ({ signal }) => commonCategoriesRetrieve(unref(id), { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof commonCategoriesRetrieve>>, TError, TData>
}

export type CommonCategoriesRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof commonCategoriesRetrieve>>>
export type CommonCategoriesRetrieveQueryError = unknown



export function useCommonCategoriesRetrieve<TData = Awaited<ReturnType<typeof commonCategoriesRetrieve>>, TError = unknown>(
 id: MaybeRef<number>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof commonCategoriesRetrieve>>, TError, TData>, fetch?: RequestInit}

 ): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCommonCategoriesRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
}






export type commonCategoriesUpdateResponse200 = {
  data: Category
  status: 200
}

export type commonCategoriesUpdateResponseSuccess = (commonCategoriesUpdateResponse200) & {
  headers: Headers;
};
;

export type commonCategoriesUpdateResponse = (commonCategoriesUpdateResponseSuccess)

export const getCommonCategoriesUpdateUrl = (id: number,) => {




  return `/api/v1/common/categories/${id}/`
}

export const commonCategoriesUpdate = async (id: number,
    category: NonReadonly<Category>, options?: RequestInit): Promise<commonCategoriesUpdateResponse> => {

  const res = await fetch(getCommonCategoriesUpdateUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      category,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonCategoriesUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commonCategoriesUpdateResponse
}




export const getCommonCategoriesUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonCategoriesUpdate>>, TError,{id: number;data: NonReadonly<Category>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof commonCategoriesUpdate>>, TError,{id: number;data: NonReadonly<Category>}, TContext> => {

const mutationKey = ['commonCategoriesUpdate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof commonCategoriesUpdate>>, {id: number;data: NonReadonly<Category>}> = (props) => {
          const {id,data} = props ?? {};

          return  commonCategoriesUpdate(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CommonCategoriesUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof commonCategoriesUpdate>>>
    export type CommonCategoriesUpdateMutationBody = NonReadonly<Category>
    export type CommonCategoriesUpdateMutationError = unknown

    export const useCommonCategoriesUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonCategoriesUpdate>>, TError,{id: number;data: NonReadonly<Category>}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof commonCategoriesUpdate>>,
        TError,
        {id: number;data: NonReadonly<Category>},
        TContext
      > => {
      return useMutation(getCommonCategoriesUpdateMutationOptions(options));
    }
    export type commonCategoriesPartialUpdateResponse200 = {
  data: Category
  status: 200
}

export type commonCategoriesPartialUpdateResponseSuccess = (commonCategoriesPartialUpdateResponse200) & {
  headers: Headers;
};
;

export type commonCategoriesPartialUpdateResponse = (commonCategoriesPartialUpdateResponseSuccess)

export const getCommonCategoriesPartialUpdateUrl = (id: number,) => {




  return `/api/v1/common/categories/${id}/`
}

export const commonCategoriesPartialUpdate = async (id: number,
    patchedCategory: NonReadonly<PatchedCategory>, options?: RequestInit): Promise<commonCategoriesPartialUpdateResponse> => {

  const res = await fetch(getCommonCategoriesPartialUpdateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchedCategory,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonCategoriesPartialUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commonCategoriesPartialUpdateResponse
}




export const getCommonCategoriesPartialUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonCategoriesPartialUpdate>>, TError,{id: number;data: NonReadonly<PatchedCategory>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof commonCategoriesPartialUpdate>>, TError,{id: number;data: NonReadonly<PatchedCategory>}, TContext> => {

const mutationKey = ['commonCategoriesPartialUpdate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof commonCategoriesPartialUpdate>>, {id: number;data: NonReadonly<PatchedCategory>}> = (props) => {
          const {id,data} = props ?? {};

          return  commonCategoriesPartialUpdate(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CommonCategoriesPartialUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof commonCategoriesPartialUpdate>>>
    export type CommonCategoriesPartialUpdateMutationBody = NonReadonly<PatchedCategory>
    export type CommonCategoriesPartialUpdateMutationError = unknown

    export const useCommonCategoriesPartialUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonCategoriesPartialUpdate>>, TError,{id: number;data: NonReadonly<PatchedCategory>}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof commonCategoriesPartialUpdate>>,
        TError,
        {id: number;data: NonReadonly<PatchedCategory>},
        TContext
      > => {
      return useMutation(getCommonCategoriesPartialUpdateMutationOptions(options));
    }
    export type commonCategoriesDestroyResponse204 = {
  data: void
  status: 204
}

export type commonCategoriesDestroyResponseSuccess = (commonCategoriesDestroyResponse204) & {
  headers: Headers;
};
;

export type commonCategoriesDestroyResponse = (commonCategoriesDestroyResponseSuccess)

export const getCommonCategoriesDestroyUrl = (id: number,) => {




  return `/api/v1/common/categories/${id}/`
}

export const commonCategoriesDestroy = async (id: number, options?: RequestInit): Promise<commonCategoriesDestroyResponse> => {

  const res = await fetch(getCommonCategoriesDestroyUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonCategoriesDestroyResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as commonCategoriesDestroyResponse
}




export const getCommonCategoriesDestroyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonCategoriesDestroy>>, TError,{id: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof commonCategoriesDestroy>>, TError,{id: number}, TContext> => {

const mutationKey = ['commonCategoriesDestroy'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof commonCategoriesDestroy>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  commonCategoriesDestroy(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CommonCategoriesDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof commonCategoriesDestroy>>>

    export type CommonCategoriesDestroyMutationError = unknown

    export const useCommonCategoriesDestroy = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonCategoriesDestroy>>, TError,{id: number}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof commonCategoriesDestroy>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getCommonCategoriesDestroyMutationOptions(options));
    }
    export type commonMerchantUsersListResponse200 = {
  data: PaginatedMerchantUserList
  status: 200
}

export type commonMerchantUsersListResponseSuccess = (commonMerchantUsersListResponse200) & {
  headers: Headers;
};
;

export type commonMerchantUsersListResponse = (commonMerchantUsersListResponseSuccess)

export const getCommonMerchantUsersListUrl = (params?: CommonMerchantUsersListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/common/merchant-users/?${stringifiedParams}` : `/api/v1/common/merchant-users/`
}

export const commonMerchantUsersList = async (params?: CommonMerchantUsersListParams, options?: RequestInit): Promise<commonMerchantUsersListResponse> => {

  const res = await fetch(getCommonMerchantUsersListUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonMerchantUsersListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commonMerchantUsersListResponse
}





export const getCommonMerchantUsersListQueryKey = (params?: MaybeRef<CommonMerchantUsersListParams>,) => {
    return [
    'api','v1','common','merchant-users', ...(params ? [params] : [])
    ] as const;
    }


export const getCommonMerchantUsersListQueryOptions = <TData = Awaited<ReturnType<typeof commonMerchantUsersList>>, TError = unknown>(params?: MaybeRef<CommonMerchantUsersListParams>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof commonMerchantUsersList>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getCommonMerchantUsersListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof commonMerchantUsersList>>> = ({ signal }) => commonMerchantUsersList(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof commonMerchantUsersList>>, TError, TData>
}

export type CommonMerchantUsersListQueryResult = NonNullable<Awaited<ReturnType<typeof commonMerchantUsersList>>>
export type CommonMerchantUsersListQueryError = unknown



export function useCommonMerchantUsersList<TData = Awaited<ReturnType<typeof commonMerchantUsersList>>, TError = unknown>(
 params?: MaybeRef<CommonMerchantUsersListParams>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof commonMerchantUsersList>>, TError, TData>, fetch?: RequestInit}

 ): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCommonMerchantUsersListQueryOptions(params,options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
}






export type commonMerchantUsersCreateResponse201 = {
  data: MerchantUser
  status: 201
}

export type commonMerchantUsersCreateResponseSuccess = (commonMerchantUsersCreateResponse201) & {
  headers: Headers;
};
;

export type commonMerchantUsersCreateResponse = (commonMerchantUsersCreateResponseSuccess)

export const getCommonMerchantUsersCreateUrl = () => {




  return `/api/v1/common/merchant-users/`
}

export const commonMerchantUsersCreate = async (merchantUser: NonReadonly<MerchantUser>, options?: RequestInit): Promise<commonMerchantUsersCreateResponse> => {

  const res = await fetch(getCommonMerchantUsersCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      merchantUser,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonMerchantUsersCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commonMerchantUsersCreateResponse
}




export const getCommonMerchantUsersCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonMerchantUsersCreate>>, TError,{data: NonReadonly<MerchantUser>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof commonMerchantUsersCreate>>, TError,{data: NonReadonly<MerchantUser>}, TContext> => {

const mutationKey = ['commonMerchantUsersCreate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof commonMerchantUsersCreate>>, {data: NonReadonly<MerchantUser>}> = (props) => {
          const {data} = props ?? {};

          return  commonMerchantUsersCreate(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CommonMerchantUsersCreateMutationResult = NonNullable<Awaited<ReturnType<typeof commonMerchantUsersCreate>>>
    export type CommonMerchantUsersCreateMutationBody = NonReadonly<MerchantUser>
    export type CommonMerchantUsersCreateMutationError = unknown

    export const useCommonMerchantUsersCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonMerchantUsersCreate>>, TError,{data: NonReadonly<MerchantUser>}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof commonMerchantUsersCreate>>,
        TError,
        {data: NonReadonly<MerchantUser>},
        TContext
      > => {
      return useMutation(getCommonMerchantUsersCreateMutationOptions(options));
    }
    export type commonMerchantUsersRetrieveResponse200 = {
  data: MerchantUser
  status: 200
}

export type commonMerchantUsersRetrieveResponseSuccess = (commonMerchantUsersRetrieveResponse200) & {
  headers: Headers;
};
;

export type commonMerchantUsersRetrieveResponse = (commonMerchantUsersRetrieveResponseSuccess)

export const getCommonMerchantUsersRetrieveUrl = (id: number,) => {




  return `/api/v1/common/merchant-users/${id}/`
}

export const commonMerchantUsersRetrieve = async (id: number, options?: RequestInit): Promise<commonMerchantUsersRetrieveResponse> => {

  const res = await fetch(getCommonMerchantUsersRetrieveUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonMerchantUsersRetrieveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commonMerchantUsersRetrieveResponse
}





export const getCommonMerchantUsersRetrieveQueryKey = (id: MaybeRef<number>,) => {
    return [
    'api','v1','common','merchant-users',id
    ] as const;
    }


export const getCommonMerchantUsersRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof commonMerchantUsersRetrieve>>, TError = unknown>(id: MaybeRef<number>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof commonMerchantUsersRetrieve>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getCommonMerchantUsersRetrieveQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof commonMerchantUsersRetrieve>>> = ({ signal }) => commonMerchantUsersRetrieve(unref(id), { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof commonMerchantUsersRetrieve>>, TError, TData>
}

export type CommonMerchantUsersRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof commonMerchantUsersRetrieve>>>
export type CommonMerchantUsersRetrieveQueryError = unknown



export function useCommonMerchantUsersRetrieve<TData = Awaited<ReturnType<typeof commonMerchantUsersRetrieve>>, TError = unknown>(
 id: MaybeRef<number>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof commonMerchantUsersRetrieve>>, TError, TData>, fetch?: RequestInit}

 ): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCommonMerchantUsersRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
}






export type commonMerchantUsersUpdateResponse200 = {
  data: MerchantUser
  status: 200
}

export type commonMerchantUsersUpdateResponseSuccess = (commonMerchantUsersUpdateResponse200) & {
  headers: Headers;
};
;

export type commonMerchantUsersUpdateResponse = (commonMerchantUsersUpdateResponseSuccess)

export const getCommonMerchantUsersUpdateUrl = (id: number,) => {




  return `/api/v1/common/merchant-users/${id}/`
}

export const commonMerchantUsersUpdate = async (id: number,
    merchantUser: NonReadonly<MerchantUser>, options?: RequestInit): Promise<commonMerchantUsersUpdateResponse> => {

  const res = await fetch(getCommonMerchantUsersUpdateUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      merchantUser,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonMerchantUsersUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commonMerchantUsersUpdateResponse
}




export const getCommonMerchantUsersUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonMerchantUsersUpdate>>, TError,{id: number;data: NonReadonly<MerchantUser>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof commonMerchantUsersUpdate>>, TError,{id: number;data: NonReadonly<MerchantUser>}, TContext> => {

const mutationKey = ['commonMerchantUsersUpdate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof commonMerchantUsersUpdate>>, {id: number;data: NonReadonly<MerchantUser>}> = (props) => {
          const {id,data} = props ?? {};

          return  commonMerchantUsersUpdate(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CommonMerchantUsersUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof commonMerchantUsersUpdate>>>
    export type CommonMerchantUsersUpdateMutationBody = NonReadonly<MerchantUser>
    export type CommonMerchantUsersUpdateMutationError = unknown

    export const useCommonMerchantUsersUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonMerchantUsersUpdate>>, TError,{id: number;data: NonReadonly<MerchantUser>}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof commonMerchantUsersUpdate>>,
        TError,
        {id: number;data: NonReadonly<MerchantUser>},
        TContext
      > => {
      return useMutation(getCommonMerchantUsersUpdateMutationOptions(options));
    }
    export type commonMerchantUsersPartialUpdateResponse200 = {
  data: MerchantUser
  status: 200
}

export type commonMerchantUsersPartialUpdateResponseSuccess = (commonMerchantUsersPartialUpdateResponse200) & {
  headers: Headers;
};
;

export type commonMerchantUsersPartialUpdateResponse = (commonMerchantUsersPartialUpdateResponseSuccess)

export const getCommonMerchantUsersPartialUpdateUrl = (id: number,) => {




  return `/api/v1/common/merchant-users/${id}/`
}

export const commonMerchantUsersPartialUpdate = async (id: number,
    patchedMerchantUser: NonReadonly<PatchedMerchantUser>, options?: RequestInit): Promise<commonMerchantUsersPartialUpdateResponse> => {

  const res = await fetch(getCommonMerchantUsersPartialUpdateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchedMerchantUser,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonMerchantUsersPartialUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commonMerchantUsersPartialUpdateResponse
}




export const getCommonMerchantUsersPartialUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonMerchantUsersPartialUpdate>>, TError,{id: number;data: NonReadonly<PatchedMerchantUser>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof commonMerchantUsersPartialUpdate>>, TError,{id: number;data: NonReadonly<PatchedMerchantUser>}, TContext> => {

const mutationKey = ['commonMerchantUsersPartialUpdate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof commonMerchantUsersPartialUpdate>>, {id: number;data: NonReadonly<PatchedMerchantUser>}> = (props) => {
          const {id,data} = props ?? {};

          return  commonMerchantUsersPartialUpdate(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CommonMerchantUsersPartialUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof commonMerchantUsersPartialUpdate>>>
    export type CommonMerchantUsersPartialUpdateMutationBody = NonReadonly<PatchedMerchantUser>
    export type CommonMerchantUsersPartialUpdateMutationError = unknown

    export const useCommonMerchantUsersPartialUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonMerchantUsersPartialUpdate>>, TError,{id: number;data: NonReadonly<PatchedMerchantUser>}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof commonMerchantUsersPartialUpdate>>,
        TError,
        {id: number;data: NonReadonly<PatchedMerchantUser>},
        TContext
      > => {
      return useMutation(getCommonMerchantUsersPartialUpdateMutationOptions(options));
    }
    export type commonMerchantUsersDestroyResponse204 = {
  data: void
  status: 204
}

export type commonMerchantUsersDestroyResponseSuccess = (commonMerchantUsersDestroyResponse204) & {
  headers: Headers;
};
;

export type commonMerchantUsersDestroyResponse = (commonMerchantUsersDestroyResponseSuccess)

export const getCommonMerchantUsersDestroyUrl = (id: number,) => {




  return `/api/v1/common/merchant-users/${id}/`
}

export const commonMerchantUsersDestroy = async (id: number, options?: RequestInit): Promise<commonMerchantUsersDestroyResponse> => {

  const res = await fetch(getCommonMerchantUsersDestroyUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonMerchantUsersDestroyResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as commonMerchantUsersDestroyResponse
}




export const getCommonMerchantUsersDestroyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonMerchantUsersDestroy>>, TError,{id: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof commonMerchantUsersDestroy>>, TError,{id: number}, TContext> => {

const mutationKey = ['commonMerchantUsersDestroy'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof commonMerchantUsersDestroy>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  commonMerchantUsersDestroy(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CommonMerchantUsersDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof commonMerchantUsersDestroy>>>

    export type CommonMerchantUsersDestroyMutationError = unknown

    export const useCommonMerchantUsersDestroy = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonMerchantUsersDestroy>>, TError,{id: number}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof commonMerchantUsersDestroy>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getCommonMerchantUsersDestroyMutationOptions(options));
    }
    export type commonProductsListResponse200 = {
  data: PaginatedProductList
  status: 200
}

export type commonProductsListResponseSuccess = (commonProductsListResponse200) & {
  headers: Headers;
};
;

export type commonProductsListResponse = (commonProductsListResponseSuccess)

export const getCommonProductsListUrl = (params?: CommonProductsListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/common/products/?${stringifiedParams}` : `/api/v1/common/products/`
}

export const commonProductsList = async (params?: CommonProductsListParams, options?: RequestInit): Promise<commonProductsListResponse> => {

  const res = await fetch(getCommonProductsListUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonProductsListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commonProductsListResponse
}





export const getCommonProductsListQueryKey = (params?: MaybeRef<CommonProductsListParams>,) => {
    return [
    'api','v1','common','products', ...(params ? [params] : [])
    ] as const;
    }


export const getCommonProductsListQueryOptions = <TData = Awaited<ReturnType<typeof commonProductsList>>, TError = unknown>(params?: MaybeRef<CommonProductsListParams>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof commonProductsList>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getCommonProductsListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof commonProductsList>>> = ({ signal }) => commonProductsList(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof commonProductsList>>, TError, TData>
}

export type CommonProductsListQueryResult = NonNullable<Awaited<ReturnType<typeof commonProductsList>>>
export type CommonProductsListQueryError = unknown



export function useCommonProductsList<TData = Awaited<ReturnType<typeof commonProductsList>>, TError = unknown>(
 params?: MaybeRef<CommonProductsListParams>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof commonProductsList>>, TError, TData>, fetch?: RequestInit}

 ): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCommonProductsListQueryOptions(params,options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
}






export type commonProductsCreateResponse201 = {
  data: Product
  status: 201
}

export type commonProductsCreateResponseSuccess = (commonProductsCreateResponse201) & {
  headers: Headers;
};
;

export type commonProductsCreateResponse = (commonProductsCreateResponseSuccess)

export const getCommonProductsCreateUrl = () => {




  return `/api/v1/common/products/`
}

export const commonProductsCreate = async (product: NonReadonly<Product>, options?: RequestInit): Promise<commonProductsCreateResponse> => {

  const res = await fetch(getCommonProductsCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      product,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonProductsCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commonProductsCreateResponse
}




export const getCommonProductsCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonProductsCreate>>, TError,{data: NonReadonly<Product>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof commonProductsCreate>>, TError,{data: NonReadonly<Product>}, TContext> => {

const mutationKey = ['commonProductsCreate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof commonProductsCreate>>, {data: NonReadonly<Product>}> = (props) => {
          const {data} = props ?? {};

          return  commonProductsCreate(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CommonProductsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof commonProductsCreate>>>
    export type CommonProductsCreateMutationBody = NonReadonly<Product>
    export type CommonProductsCreateMutationError = unknown

    export const useCommonProductsCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonProductsCreate>>, TError,{data: NonReadonly<Product>}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof commonProductsCreate>>,
        TError,
        {data: NonReadonly<Product>},
        TContext
      > => {
      return useMutation(getCommonProductsCreateMutationOptions(options));
    }
    export type commonProductsRetrieveResponse200 = {
  data: Product
  status: 200
}

export type commonProductsRetrieveResponseSuccess = (commonProductsRetrieveResponse200) & {
  headers: Headers;
};
;

export type commonProductsRetrieveResponse = (commonProductsRetrieveResponseSuccess)

export const getCommonProductsRetrieveUrl = (id: number,) => {




  return `/api/v1/common/products/${id}/`
}

export const commonProductsRetrieve = async (id: number, options?: RequestInit): Promise<commonProductsRetrieveResponse> => {

  const res = await fetch(getCommonProductsRetrieveUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonProductsRetrieveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commonProductsRetrieveResponse
}





export const getCommonProductsRetrieveQueryKey = (id: MaybeRef<number>,) => {
    return [
    'api','v1','common','products',id
    ] as const;
    }


export const getCommonProductsRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof commonProductsRetrieve>>, TError = unknown>(id: MaybeRef<number>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof commonProductsRetrieve>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getCommonProductsRetrieveQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof commonProductsRetrieve>>> = ({ signal }) => commonProductsRetrieve(unref(id), { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof commonProductsRetrieve>>, TError, TData>
}

export type CommonProductsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof commonProductsRetrieve>>>
export type CommonProductsRetrieveQueryError = unknown



export function useCommonProductsRetrieve<TData = Awaited<ReturnType<typeof commonProductsRetrieve>>, TError = unknown>(
 id: MaybeRef<number>, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof commonProductsRetrieve>>, TError, TData>, fetch?: RequestInit}

 ): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCommonProductsRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & { queryKey: QueryKey };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
}






export type commonProductsUpdateResponse200 = {
  data: Product
  status: 200
}

export type commonProductsUpdateResponseSuccess = (commonProductsUpdateResponse200) & {
  headers: Headers;
};
;

export type commonProductsUpdateResponse = (commonProductsUpdateResponseSuccess)

export const getCommonProductsUpdateUrl = (id: number,) => {




  return `/api/v1/common/products/${id}/`
}

export const commonProductsUpdate = async (id: number,
    product: NonReadonly<Product>, options?: RequestInit): Promise<commonProductsUpdateResponse> => {

  const res = await fetch(getCommonProductsUpdateUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      product,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonProductsUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commonProductsUpdateResponse
}




export const getCommonProductsUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonProductsUpdate>>, TError,{id: number;data: NonReadonly<Product>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof commonProductsUpdate>>, TError,{id: number;data: NonReadonly<Product>}, TContext> => {

const mutationKey = ['commonProductsUpdate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof commonProductsUpdate>>, {id: number;data: NonReadonly<Product>}> = (props) => {
          const {id,data} = props ?? {};

          return  commonProductsUpdate(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CommonProductsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof commonProductsUpdate>>>
    export type CommonProductsUpdateMutationBody = NonReadonly<Product>
    export type CommonProductsUpdateMutationError = unknown

    export const useCommonProductsUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonProductsUpdate>>, TError,{id: number;data: NonReadonly<Product>}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof commonProductsUpdate>>,
        TError,
        {id: number;data: NonReadonly<Product>},
        TContext
      > => {
      return useMutation(getCommonProductsUpdateMutationOptions(options));
    }
    export type commonProductsPartialUpdateResponse200 = {
  data: Product
  status: 200
}

export type commonProductsPartialUpdateResponseSuccess = (commonProductsPartialUpdateResponse200) & {
  headers: Headers;
};
;

export type commonProductsPartialUpdateResponse = (commonProductsPartialUpdateResponseSuccess)

export const getCommonProductsPartialUpdateUrl = (id: number,) => {




  return `/api/v1/common/products/${id}/`
}

export const commonProductsPartialUpdate = async (id: number,
    patchedProduct: NonReadonly<PatchedProduct>, options?: RequestInit): Promise<commonProductsPartialUpdateResponse> => {

  const res = await fetch(getCommonProductsPartialUpdateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchedProduct,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonProductsPartialUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as commonProductsPartialUpdateResponse
}




export const getCommonProductsPartialUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonProductsPartialUpdate>>, TError,{id: number;data: NonReadonly<PatchedProduct>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof commonProductsPartialUpdate>>, TError,{id: number;data: NonReadonly<PatchedProduct>}, TContext> => {

const mutationKey = ['commonProductsPartialUpdate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof commonProductsPartialUpdate>>, {id: number;data: NonReadonly<PatchedProduct>}> = (props) => {
          const {id,data} = props ?? {};

          return  commonProductsPartialUpdate(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CommonProductsPartialUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof commonProductsPartialUpdate>>>
    export type CommonProductsPartialUpdateMutationBody = NonReadonly<PatchedProduct>
    export type CommonProductsPartialUpdateMutationError = unknown

    export const useCommonProductsPartialUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonProductsPartialUpdate>>, TError,{id: number;data: NonReadonly<PatchedProduct>}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof commonProductsPartialUpdate>>,
        TError,
        {id: number;data: NonReadonly<PatchedProduct>},
        TContext
      > => {
      return useMutation(getCommonProductsPartialUpdateMutationOptions(options));
    }
    export type commonProductsDestroyResponse204 = {
  data: void
  status: 204
}

export type commonProductsDestroyResponseSuccess = (commonProductsDestroyResponse204) & {
  headers: Headers;
};
;

export type commonProductsDestroyResponse = (commonProductsDestroyResponseSuccess)

export const getCommonProductsDestroyUrl = (id: number,) => {




  return `/api/v1/common/products/${id}/`
}

export const commonProductsDestroy = async (id: number, options?: RequestInit): Promise<commonProductsDestroyResponse> => {

  const res = await fetch(getCommonProductsDestroyUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: commonProductsDestroyResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as commonProductsDestroyResponse
}




export const getCommonProductsDestroyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonProductsDestroy>>, TError,{id: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof commonProductsDestroy>>, TError,{id: number}, TContext> => {

const mutationKey = ['commonProductsDestroy'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof commonProductsDestroy>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  commonProductsDestroy(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CommonProductsDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof commonProductsDestroy>>>

    export type CommonProductsDestroyMutationError = unknown

    export const useCommonProductsDestroy = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof commonProductsDestroy>>, TError,{id: number}, TContext>, fetch?: RequestInit}
 ): UseMutationReturnType<
        Awaited<ReturnType<typeof commonProductsDestroy>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getCommonProductsDestroyMutationOptions(options));
    }
