/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Comeat Backend API
 * 多租户餐饮外卖系统后端API文档
 * OpenAPI spec version: 1.0.0
 */
export interface Category {
  readonly id: number;
  /** @maxLength 32 */
  name: string;
  /**
     * @minimum -32768
     * @maximum 32767
     */
  sort?: number;
  is_show?: boolean;
  readonly created_at: string;
  readonly updated_at: string;
  readonly is_deleted: boolean;
}

export interface Product {
  readonly id: number;
  readonly category: Category;
  category_id: number;
  /** @maxLength 64 */
  name: string;
  /** @maxLength 200 */
  image: string;
  images?: unknown | null;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  price: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  original_price: string;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
  stock?: number;
  readonly sales: number;
  description?: string;
  is_on_sale?: boolean;
  /** @nullable */
  on_sale_at?: string | null;
  /**
     * @minimum -32768
     * @maximum 32767
     */
  sort?: number;
  readonly created_at: string;
  readonly updated_at: string;
  readonly is_deleted: boolean;
}

export interface Cart {
  readonly id: number;
  customer: number;
  readonly product: Product;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
  quantity?: number;
  is_selected?: boolean;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  readonly price_snapshot: string;
  readonly created_at: string;
  readonly updated_at: string;
  readonly is_deleted: boolean;
}

/**
 * * `reduce` - 满减券
* `discount` - 折扣券
* `points` - 积分券
 */
export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];


export const TypeEnum = {
  reduce: 'reduce',
  discount: 'discount',
  points: 'points',
} as const;

export interface Coupon {
  readonly id: number;
  /** @maxLength 64 */
  name: string;
  type: TypeEnum;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  min_amount?: string;
  /**
     * @nullable
     * @pattern ^-?\d{0,8}(?:\.\d{0,2})?$
     */
  reduce_amount?: string | null;
  /**
     * @nullable
     * @pattern ^-?\d{0,2}(?:\.\d{0,1})?$
     */
  discount?: string | null;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     * @nullable
     */
  points_value?: number | null;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
  total_count: number;
  readonly used_count: number;
  start_time: string;
  end_time: string;
  readonly created_at: string;
  readonly updated_at: string;
  readonly is_deleted: boolean;
}

export interface Customer {
  readonly id: number;
  /** @maxLength 64 */
  wechat_openid: string;
  /**
     * @maxLength 64
     * @nullable
     */
  wechat_unionid?: string | null;
  /**
     * @maxLength 11
     * @nullable
     */
  phone?: string | null;
  /**
     * @maxLength 200
     * @nullable
     */
  avatar?: string | null;
  /**
     * @maxLength 32
     * @nullable
     */
  nickname?: string | null;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
  points?: number;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  balance?: string;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
  total_orders?: number;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  total_amount?: string;
  readonly created_at: string;
  /** @nullable */
  readonly last_login: string | null;
  readonly is_deleted: boolean;
}

export interface CustomerAddress {
  readonly id: number;
  customer: number;
  /** @maxLength 20 */
  receiver: string;
  /** @maxLength 11 */
  phone: string;
  /** @maxLength 20 */
  province: string;
  /** @maxLength 20 */
  city: string;
  /** @maxLength 20 */
  district: string;
  /** @maxLength 255 */
  detail: string;
  is_default?: boolean;
  readonly created_at: string;
  readonly updated_at: string;
  readonly is_deleted: boolean;
}

export interface MerchantUser {
  readonly id: number;
  /** @maxLength 11 */
  phone: string;
  /**
     * @maxLength 32
     * @nullable
     */
  real_name?: string | null;
  is_staff?: boolean;
  is_active?: boolean;
  readonly created_at: string;
  readonly updated_at: string;
  readonly is_deleted: boolean;
}

/**
 * * `pending_pay` - 待支付
* `pending_accept` - 待接单
* `delivering` - 配送中
* `completed` - 已完成
* `cancelled` - 已取消
* `refunding` - 退款中
* `refunded` - 已退款
 */
export type OrderStatusEnum = typeof OrderStatusEnum[keyof typeof OrderStatusEnum];


export const OrderStatusEnum = {
  pending_pay: 'pending_pay',
  pending_accept: 'pending_accept',
  delivering: 'delivering',
  completed: 'completed',
  cancelled: 'cancelled',
  refunding: 'refunding',
  refunded: 'refunded',
} as const;

export interface OrderItem {
  readonly id: number;
  order: number;
  /** @nullable */
  product?: number | null;
  /** @maxLength 64 */
  product_name: string;
  /** @maxLength 200 */
  product_image: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  price: string;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
  quantity?: number;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  subtotal: string;
  readonly created_at: string;
  readonly updated_at: string;
  readonly is_deleted: boolean;
}

export interface Order {
  readonly id: number;
  readonly order_no: string;
  customer: number;
  address: unknown;
  /** @nullable */
  user_coupon?: number | null;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  total_amount: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  coupon_amount?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  delivery_fee?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  pay_amount: string;
  status?: OrderStatusEnum;
  /** @maxLength 200 */
  remark?: string;
  /** @nullable */
  pay_time?: string | null;
  /** @nullable */
  accept_time?: string | null;
  /** @nullable */
  finish_time?: string | null;
  /** @nullable */
  cancel_time?: string | null;
  readonly items: readonly OrderItem[];
  readonly created_at: string;
  readonly updated_at: string;
  readonly is_deleted: boolean;
}

export interface PaginatedCartList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Cart[];
}

export interface PaginatedCategoryList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Category[];
}

export interface PaginatedCouponList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Coupon[];
}

export interface PaginatedCustomerAddressList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: CustomerAddress[];
}

export interface PaginatedCustomerList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Customer[];
}

export interface PaginatedMerchantUserList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: MerchantUser[];
}

export interface PaginatedOrderItemList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: OrderItem[];
}

export interface PaginatedOrderList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Order[];
}

/**
 * * `wechat` - 微信支付
* `cash` - 货到付款
 */
export type PayTypeEnum = typeof PayTypeEnum[keyof typeof PayTypeEnum];


export const PayTypeEnum = {
  wechat: 'wechat',
  cash: 'cash',
} as const;

/**
 * * `pending` - 待支付
* `success` - 支付成功
* `fail` - 支付失败
 */
export type PaymentStatusEnum = typeof PaymentStatusEnum[keyof typeof PaymentStatusEnum];


export const PaymentStatusEnum = {
  pending: 'pending',
  success: 'success',
  fail: 'fail',
} as const;

export interface Payment {
  readonly id: number;
  order: number;
  customer: number;
  readonly pay_no: string;
  pay_type: PayTypeEnum;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  pay_amount: string;
  status?: PaymentStatusEnum;
  /**
     * @maxLength 64
     * @nullable
     */
  transaction_id?: string | null;
  callback_data?: unknown;
  readonly created_at: string;
  readonly updated_at: string;
  readonly is_deleted: boolean;
}

export interface PaginatedPaymentList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Payment[];
}

export interface PaginatedProductList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Product[];
}

/**
 * * `pending` - 退款中
* `success` - 退款成功
* `fail` - 退款失败
 */
export type RefundStatusEnum = typeof RefundStatusEnum[keyof typeof RefundStatusEnum];


export const RefundStatusEnum = {
  pending: 'pending',
  success: 'success',
  fail: 'fail',
} as const;

export interface Refund {
  readonly id: number;
  order: number;
  payment: number;
  readonly refund_no: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  refund_amount: string;
  /** @maxLength 200 */
  reason: string;
  status?: RefundStatusEnum;
  readonly created_at: string;
  readonly updated_at: string;
  readonly is_deleted: boolean;
}

export interface PaginatedRefundList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Refund[];
}

/**
 * * `unused` - 未使用
* `used` - 已使用
* `expired` - 已过期
 */
export type UserCouponStatusEnum = typeof UserCouponStatusEnum[keyof typeof UserCouponStatusEnum];


export const UserCouponStatusEnum = {
  unused: 'unused',
  used: 'used',
  expired: 'expired',
} as const;

export interface UserCoupon {
  readonly id: number;
  customer: number;
  readonly coupon: Coupon;
  status?: UserCouponStatusEnum;
  /** @nullable */
  used_time?: string | null;
  expire_time: string;
  readonly created_at: string;
  readonly updated_at: string;
  readonly is_deleted: boolean;
}

export interface PaginatedUserCouponList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: UserCoupon[];
}

export interface PatchedCart {
  readonly id?: number;
  customer?: number;
  readonly product?: Product;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
  quantity?: number;
  is_selected?: boolean;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  readonly price_snapshot?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  readonly is_deleted?: boolean;
}

export interface PatchedCategory {
  readonly id?: number;
  /** @maxLength 32 */
  name?: string;
  /**
     * @minimum -32768
     * @maximum 32767
     */
  sort?: number;
  is_show?: boolean;
  readonly created_at?: string;
  readonly updated_at?: string;
  readonly is_deleted?: boolean;
}

export interface PatchedCoupon {
  readonly id?: number;
  /** @maxLength 64 */
  name?: string;
  type?: TypeEnum;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  min_amount?: string;
  /**
     * @nullable
     * @pattern ^-?\d{0,8}(?:\.\d{0,2})?$
     */
  reduce_amount?: string | null;
  /**
     * @nullable
     * @pattern ^-?\d{0,2}(?:\.\d{0,1})?$
     */
  discount?: string | null;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     * @nullable
     */
  points_value?: number | null;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
  total_count?: number;
  readonly used_count?: number;
  start_time?: string;
  end_time?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  readonly is_deleted?: boolean;
}

export interface PatchedCustomer {
  readonly id?: number;
  /** @maxLength 64 */
  wechat_openid?: string;
  /**
     * @maxLength 64
     * @nullable
     */
  wechat_unionid?: string | null;
  /**
     * @maxLength 11
     * @nullable
     */
  phone?: string | null;
  /**
     * @maxLength 200
     * @nullable
     */
  avatar?: string | null;
  /**
     * @maxLength 32
     * @nullable
     */
  nickname?: string | null;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
  points?: number;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  balance?: string;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
  total_orders?: number;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  total_amount?: string;
  readonly created_at?: string;
  /** @nullable */
  readonly last_login?: string | null;
  readonly is_deleted?: boolean;
}

export interface PatchedCustomerAddress {
  readonly id?: number;
  customer?: number;
  /** @maxLength 20 */
  receiver?: string;
  /** @maxLength 11 */
  phone?: string;
  /** @maxLength 20 */
  province?: string;
  /** @maxLength 20 */
  city?: string;
  /** @maxLength 20 */
  district?: string;
  /** @maxLength 255 */
  detail?: string;
  is_default?: boolean;
  readonly created_at?: string;
  readonly updated_at?: string;
  readonly is_deleted?: boolean;
}

export interface PatchedMerchantUser {
  readonly id?: number;
  /** @maxLength 11 */
  phone?: string;
  /**
     * @maxLength 32
     * @nullable
     */
  real_name?: string | null;
  is_staff?: boolean;
  is_active?: boolean;
  readonly created_at?: string;
  readonly updated_at?: string;
  readonly is_deleted?: boolean;
}

export interface PatchedOrder {
  readonly id?: number;
  readonly order_no?: string;
  customer?: number;
  address?: unknown;
  /** @nullable */
  user_coupon?: number | null;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  total_amount?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  coupon_amount?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  delivery_fee?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  pay_amount?: string;
  status?: OrderStatusEnum;
  /** @maxLength 200 */
  remark?: string;
  /** @nullable */
  pay_time?: string | null;
  /** @nullable */
  accept_time?: string | null;
  /** @nullable */
  finish_time?: string | null;
  /** @nullable */
  cancel_time?: string | null;
  readonly items?: readonly OrderItem[];
  readonly created_at?: string;
  readonly updated_at?: string;
  readonly is_deleted?: boolean;
}

export interface PatchedOrderItem {
  readonly id?: number;
  order?: number;
  /** @nullable */
  product?: number | null;
  /** @maxLength 64 */
  product_name?: string;
  /** @maxLength 200 */
  product_image?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  price?: string;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
  quantity?: number;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  subtotal?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  readonly is_deleted?: boolean;
}

export interface PatchedPayment {
  readonly id?: number;
  order?: number;
  customer?: number;
  readonly pay_no?: string;
  pay_type?: PayTypeEnum;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  pay_amount?: string;
  status?: PaymentStatusEnum;
  /**
     * @maxLength 64
     * @nullable
     */
  transaction_id?: string | null;
  callback_data?: unknown;
  readonly created_at?: string;
  readonly updated_at?: string;
  readonly is_deleted?: boolean;
}

export interface PatchedProduct {
  readonly id?: number;
  readonly category?: Category;
  category_id?: number;
  /** @maxLength 64 */
  name?: string;
  /** @maxLength 200 */
  image?: string;
  images?: unknown | null;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  price?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  original_price?: string;
  /**
     * @minimum -2147483648
     * @maximum 2147483647
     */
  stock?: number;
  readonly sales?: number;
  description?: string;
  is_on_sale?: boolean;
  /** @nullable */
  on_sale_at?: string | null;
  /**
     * @minimum -32768
     * @maximum 32767
     */
  sort?: number;
  readonly created_at?: string;
  readonly updated_at?: string;
  readonly is_deleted?: boolean;
}

export interface PatchedRefund {
  readonly id?: number;
  order?: number;
  payment?: number;
  readonly refund_no?: string;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  refund_amount?: string;
  /** @maxLength 200 */
  reason?: string;
  status?: RefundStatusEnum;
  readonly created_at?: string;
  readonly updated_at?: string;
  readonly is_deleted?: boolean;
}

export interface PatchedUserCoupon {
  readonly id?: number;
  customer?: number;
  readonly coupon?: Coupon;
  status?: UserCouponStatusEnum;
  /** @nullable */
  used_time?: string | null;
  expire_time?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  readonly is_deleted?: boolean;
}

export type BusinessCartsListParams = {
/**
 * 分页结果集中的页码。
 */
page?: number;
};

export type BusinessCouponsListParams = {
/**
 * 分页结果集中的页码。
 */
page?: number;
};

export type BusinessCustomerAddressesListParams = {
/**
 * 分页结果集中的页码。
 */
page?: number;
};

export type BusinessCustomersListParams = {
/**
 * 分页结果集中的页码。
 */
page?: number;
};

export type BusinessOrderItemsListParams = {
/**
 * 分页结果集中的页码。
 */
page?: number;
};

export type BusinessOrdersListParams = {
/**
 * 分页结果集中的页码。
 */
page?: number;
};

export type BusinessPaymentsListParams = {
/**
 * 分页结果集中的页码。
 */
page?: number;
};

export type BusinessRefundsListParams = {
/**
 * 分页结果集中的页码。
 */
page?: number;
};

export type BusinessUserCouponsListParams = {
/**
 * 分页结果集中的页码。
 */
page?: number;
};

export type CommonCategoriesListParams = {
/**
 * 分页结果集中的页码。
 */
page?: number;
};

export type CommonMerchantUsersListParams = {
/**
 * 分页结果集中的页码。
 */
page?: number;
};

export type CommonProductsListParams = {
/**
 * 分页结果集中的页码。
 */
page?: number;
};

